### ISSUE TITLE
Imposible to execute

### ISSUE THREAD

**Issue by Ayo91** [ltwlf/azure-functions-puppeteer#1]
After the deployment using CI with the deployment center through a Bitbucket repo, this error is generated when I execute the function:

Exception while executing function: Functions.XXXX Result: Failure
Exception: Error: Failed to launch chrome!
/home/site/wwwroot/node_modules/puppeteer/.local-chromium/linux-674921/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

Its a Linux function

Any idea?

**Comment by ltwlf** [comment]
Hello Ayo91, 

I just used the container in a another project and it worked. I also updated the project to use the latest Microsoft function base image. 
I recommend to add puppeteer with npm i puppeteer --save as dependency to you Azure Function.

Best wishes
Christian
