### ISSUE TITLE
Chromium revision is not downloaded

### ISSUE THREAD

**Issue by enstulen** [ltwlf/azure-functions-puppeteer#3]
When I run the function on Azure, I get this error: 

> Result: Failure Exception: Error: Could not find browser revision 782078. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary. Stack: Error: Could not find browser revision 782078. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary. at ChromeLauncher.launch (D:\home\site\wwwroot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:86:23)

It works fine locally, but not when I deploy it. Any idea how to fix this? Any help would be very much appreciated 😊

**Comment by ltwlf** [comment]
Just to be sure, the function only runs in the docker container in azure, because of the dependencies. Did you run it as azure function with custom container?

**Comment by enstulen** [comment]
You're right. I wasn't actually running the docker container. My bad! However, I still can't make it work. Here's the steps I go through: 

First, I create a new Function App in the portal and choose the option to publish through a docker container. Then I create the project like so: 

1 `func init LocalFunctionsProject --worker-runtime node --language javascript --docker`
2. `cd LocalFunctionsProject`
3. And a new function: `func new --name HttpExample --template "HTTP trigger"`
4. I replace the `.Dockerfile` with 

```
FROM leitwolf/azure-functions-puppeteer:latest

COPY . /home/site/wwwroot
``` 

and update the function to what you have in the readme.
5. `npm install puppeteer`

Then I build the image and publish it to the container registry:

1. `docker build --tag test-function . `
2. `docker tag test-function {myregistry}.azurecr.io/klp-test-function`
3. `docker push {myregistry}.azurecr.io/klp-test-function`

I then go to container settings in the Function App and select image source `Azure Container Registry` and select the newly uploaded image. (and select contindous deployment)

 When I run the newly deployed function, it returns 500 and the monitoring displays this error message: 

> Result: Failure Exception: Worker was unable to load function HttpExample: 'TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function' Stack: TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function at promisify (internal/util.js:214:11) at Object.<anonymous> (/home/site/wwwroot/node_modules/extract-zip/index.js:11:18) at Module._compile (module.js:653:30) at Object.Module._extensions..js (module.js:664:10) at Module.load (module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Object.<anonymous> (/home/site/wwwroot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:48:39)

Am I doing something wrong again? 😅

**Comment by enstulen** [comment]
It worked with a new Dockerfile with updated azure functions and new dependencies. 
```
FROM mcr.microsoft.com/azure-functions/node:3.0-node12-appservice

RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
    libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
    libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
    libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

COPY . /home/site/wwwroot
WORKDIR /home/site/wwwroot
RUN npm install puppeteer
```

The dependencies were found here: https://github.com/puppeteer/puppeteer/blob/main/.ci/node12/Dockerfile.linux
